type TCommandName = 
    | "create" 
    | "add"
    | "index"
    | "primary"
    | "unique"
    | "foreign"
    | "drop"
    | "dropIfExists"
    | "dropColumn"
    | "dropPrimary"
    | "dropUnique"
    | "dropIndex"
    | "dropForeign"
    | "rename"
    | "renameIndex"
    | "renameColumn"